### ISSUE TITLE
TEAM 4 - Database refactoring

### ISSUE THREAD

**Issue by OrdepA17** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#110]
Discuss with the other teams what features have been implemented using the backend to analyze and refactor functionalities to be more effective. This task also includes updating the database tables and entity relations. **After discussing with the teams, if there are more tables to be added a separate task for new table creations will be created.** 

Task worth: 36pts (6 pts High Urgency * 6 pts Hard Difficulty)

**Comment by Jeisen515** [comment]
Finished the assigned task and will include key points of it.

- Renamed the course_schedule table to tutoring_courses to avoid misunderstandings
- Dropped the active_courses and courses_tutoring columns from the users table due to them being redundant for the project.
- Added a student-course-tutor relationship table which will let the students enroll the courses with an specific tutor.
- Updated Entity Relationship Table below: 
![Screenshot 2023-10-02 001658](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-tutoring-app/assets/72313954/ed5fa51c-bab3-4c00-b79b-a7d722b37f05)
