### ISSUE TITLE
Research options for how querying the university's courses will work

### ISSUE THREAD

**Issue by panchi64** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#26]
This task involves understanding the requirements of the services page and researching/coming to the conclusion as to what type of database would be more viable given the team's current skillsets. Documentation of the research is required.

Task worth: 16pts (4 from medium priority * 4 from intermediate difficulty)

**Comment by Jonathan-Rod** [comment]
Do we already know the properties of this tutor component?

**Comment by OrdepA17** [comment]
This task will be changed into a more technical task. Since discussions of database options are occurring, the query creation of the different course selections would be the main priority.  This way the proper information about the courses would be displayed on the pages that require it.  This urgency and difficulty have been adjusted due to schedule changes, making the task harder to complete.

Task worth: 48pts (6 from high priority * 8 from advanced difficulty)

**Comment by JadiellMV** [comment]
The task is completed, here's the documentation. 
https://docs.google.com/document/d/1rxJn2sYcO_lE6QDfjbeloS0hR4sdzL29qLKynp_mZ7o/edit?usp=sharing

**Comment by Jonathan-Rod** [comment]
> The task is completed, here's the documentation. 
> https://docs.google.com/document/d/1rxJn2sYcO_lE6QDfjbeloS0hR4sdzL29qLKynp_mZ7o/edit?usp=sharing

your document is private

**Comment by JadiellMV** [comment]
Sorry, its fixed.

**Comment by OrdepA17** [comment]
Points have been awarded, good work!
