### ISSUE TITLE
TEAM 4 - API configuration

### ISSUE THREAD

**Issue by panchi64** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#32]
This task involves the creation of a basic api to communicate with a chosen database structure.

Task worth: 24pts (4 pts from medium priority * 6 pts from hard difficulty)

**Comment by OrdepA17** [comment]
This task involves the creation of a basic API to communicate with a chosen database structure. This can also be tested using the Postman API (which I would recommend). I have attached some links that can help you get started. The points have been adjusted due to changes in the schedule. 

Task worth: 36pts (6 pts from high priority * 6 pts from hard difficulty)

https://www.dataquest.io/blog/python-api-tutorial/
https://www.postman.com/product/what-is-postman/#:~:text=Postman%20is%20an%20API%20platform,can%20create%20better%20APIs%E2%80%94faster.

**Comment by OrdepA17** [comment]
Although proof was not submitted in the comments, I personally witnessed the task being completed and can be found in the Team4_API_JS branch. Good work and the points were already awarded as of yesterday!
