### ISSUE TITLE
TEAM 4 - Database query creation

### ISSUE THREAD

**Issue by panchi64** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#39]
This task involves the creation of the queries that the API will use to enable the desired functionality.

Task worth: 16pts (4 pts from medium priority * 4 pts from intermediate difficulty)

**Comment by OrdepA17** [comment]
The database shall be part of the next sprint so urgency has been adjusted to high. Team 4 will work on different query creation during this sprint. Feel free to add any resources found that may facilitate the work of the tasks in the comments, as well as any ideas or discussions regarding the database. Similarly, you may go to the discussion tab and see the selection of the technologies that will be used.

Task worth has been adjusted due to sprint changes and difficulty adjusted since priority has been increased and due date is sooner than anticipated. 

Task worth: 48 pts (8pts from high priority + 6pts from intermediate difficulty)

**Comment by OrdepA17** [comment]
This task is too ambiguous and shall be divided into more detailed tasks while maintaining its importance.  *NOTE* JUST BECAUSE THIS TASK WAS CLOSED DOES NOT MEAN IT WAS COMPLETED, IT IS JUST BEING REPLACED BY ANOTHER TASK!!!!!!!!!!!!!!
