### ISSUE TITLE
TEAM 4 - API integration with database

### ISSUE THREAD

**Issue by panchi64** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#40]
This task envolves connecting the API to the database via the determined queries and verifying that everything works as expected.

Task worth: 16pts (4pts for medium priority * 4pts for intermediate difficulty)

**Comment by OrdepA17** [comment]
This task involves connecting the API to the database via the determined queries and verifying that everything works as expected. This task has been assigned to Team 4 and points have been adjusted due to schedule change. 

Task worth: 36pts (6pts for medium priority * 6pts for intermediate difficulty)

**Comment by OrdepA17** [comment]
Good work! Points have been awarded
