### ISSUE TITLE
TEAM 1 - Generate a report on what data does the profile page needs from the db

### ISSUE THREAD

**Issue by print-Eruki** [uprm-inso4101-2023-2024-S1/semester-project-tutoring-app#75]
Use this opportunity to find what type of database is best for our used case and provide pros and cons, collaborate with the backend tech stack decision in discussion #68 

Task points: 5 (Difficulty) * 5 (Priority) = 25 pts

**Comment by Ezequiel-Mendez** [comment]
Suggestion:  A Postgres-based database is the best choice. It is robust, scalable, reliable, has many features, and has vast community support. It can also be integrated easily with React Native, the framework chosen for this project, and has solid documentation (https://www.postgresql.org/docs/). In addition to this, it allows for complex querying in contrast to other databases like SQLite.

In regard to what the profile page would need from the database, it would be the following:

Users Table:

  Fields:
  id (Primary Key)
  name (VARCHAR)
  email (VARCHAR)
  password (VARCHAR)
  profile_picture (VARCHAR)
  location (VARCHAR)
  bio (VARCHAR)
  role (VARCHAR)

Subjects Table:

    Fields:
    id (Primary Key)
    subject_name (VARCHAR)
    Tutor_Subjects Table:
    Fields:
    tutor_id (Foreign Key, References Users.id)
    subject_id (Foreign Key, References Subjects.id)

Availability Table:

    Fields:
    id (Primary Key)
    tutor_id (Foreign Key, References Users.id)
    day_of_week (VARCHAR)
    start_time (TIME)
    end_time (TIME)

Ratings_and_Reviews Table:

    Fields:
    id (Primary Key)
    tutor_id (Foreign Key, References Users.id)
    student_id (Foreign Key, References Users.id)
    rating (INT)
    review (VARCHAR)


For the profile picture, it is best to store the image in another file system and to save the path or url to that image instead of storing the image in a Binary Large Object (BLOB) type in the table since this can affect the performance of the database once you have a large amount of images to be stored.
